using DAL;
using Microsoft.AspNetCore.Http;
using Model.DomainModel;
using Model.DomainModel.MemberModels;
using Model.ViewModel;
using Model.ViewModel.MemberModels;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace BAL.Interface
{
    public interface IMemberBAL
    {
        #region Common
        public List<MemberGridViewModel> MemberGridGet(MemberFilterModel filter, out int TotalCount);
        public List<MemberGridViewModel> MemberGridGetforLocalBody(MemberFilterModel filter, out int TotalCount);
        public List<DatewiseApprovalModel> DatewiseAprovedList(MemberFilterModel filter, out int TotalCount);
        #region reports

        //modified by Sivasankar K on 20-12-2025 for viewing datewise approved report
        public List<GCCReportModels> GetGCCReport(MemberFilterModel filter,out int totalCount);
        public List<LocalBodyReportModel> GetNameofLocalBodyReport(MemberFilterModel filter,out int totalCount);
        public List<BlockWiseReportModel> GetBlockWiseReport(MemberFilterModel filter,out int totalCount);
        public List<AllLocalBodyReportModel> GetAllLocalBodySummary();
        public List<DepartmentWiseApprovalModel> GetDatewiseApprovedMembers(MemberFilterModel filter, out int TotalCount);

        public List<FamilyMemberApprovalModel> FamilyMembersAprovedList(MemberFilterModel filter, out int TotalCount);

        public List<GetDatewiseProgressiveReportModel> GetDatewiseProgressiveReport(MemberFilterModel filter, out int TotalCount);
        
            #endregion reports

        public MemberFormGeneralInfo MemberFormGeneralInfo_Get(string MemberId);
        public MemberGetModels Member_Get_All(string MemberId);
        public void Member_Save_All(MemberSaveAllModels model, AuditColumnsModel audit);
        public MemberIdCodeGetModel Application_Detail_Member_Init_SaveUpdate(MemberInitSaveModel model, AuditColumnsModel audit);
        #endregion Common

        #region Member
        public MemberDetailsFormModel Member_Form_Get(string MemberId);
        public string Application_Detail_Member_SaveUpdate(MemberDetailsSaveModel model, AuditColumnsModel audit);
        public MemberDetailsModel Member_Get(string MemberId);
        public MemberModels Get_Member_All_Details_By_MemberId(string memberId);
        public MemberViewModelExisting Get_Member_All_Saved_Details_By_MemberId(string memberId);
        public MemberDiffViewModel Get_Member_All_Saved_Details_Diff_By_MemberId(string MemberId);
        public MemberDetailsViewModelExisting Get_Member_View(string MemberId);
        public string LookupMemberInLocal(string SearchString);
        public int UpdateMemberCodeRunningNumber(string MemberId, int AutoGeneratedNumber);
        public bool IsMobileNumberExist(string MemberId, string MobileNumber);
        public List<SelectListItem> Application_NameOfTheLocalBody_Select_Get(string MemberId, string DistrictId);
        #endregion Member

        #region Family Member Import
        //public string GetFamilyMemberImportProcessStatus();
        //public void FamilyMemberImport(IFormFile postedFile, string path, AuditColumnsModel audit);
        public ImportResultModel FamilyMemberImport(IFormFile file, AuditColumnsModel audit);

        #endregion Member Import

        #region Organization
        public OrganizationDetailFormModel Organization_Form_Get(string MemberId);
        public string Application_Detail_Organization_SaveUpdate(OrganizationDetailSaveModel model, AuditColumnsModel audit);
        public OrganizationDetailModel Member_Organization_Get(string Id = "", string MemberId = "");
        #endregion Organization

        #region Family
        public FamilyMemberFormModel Family_Form_Get(string FamilyMemberId);
        public string Application_Detail_Family_SaveUpdate(FamilyMemberSaveModel model, AuditColumnsModel audit);
        public List<FamilyMemberModel> Member_Family_Get(string FamilyMemberId, string MemberId, bool IsTemp = false);
        public string Member_New_Family_Member_Save(string MemberId, string MemberName, AuditColumnsModel model);
        public int Family_Member_Has_Application(string FamilyMemberId);
        #endregion Family

        #region Bank
        public BankDetailFormModel Bank_Form_Get(string MemberId);
        public string Application_Detail_Bank_SaveUpdate(BankDetailSaveModel model, AuditColumnsModel audit);
        public BankDetailModel Member_Bank_Get(string Id = "", string MemberId = "");
        #endregion Bank

        #region Application_Member_Bank
        public string Application_Member_Bank_SaveUpdate(ApplicationBankDetailSaveModel model, AuditColumnsModel audit);
        public ApplicationBankModel Application_Member_Bank_Get(string Id = "", string Application_Id = "");
        #endregion Application_Member_Bank

        #region Address
        public AddressDetailFormModel Address_Form_Get(string MemberId, string AddressType);
        public string Member_Address_Master_SaveUpdate(ApplicationAddressMaster model, AuditColumnsModel audit);
        public List<ApplicationAddressMaster> Member_Address_Master_Get(string Id = "", string MemberId = "", string AddressType = "");
        #endregion Address

        #region Member Search
        public bool Search_Member(string SearchText, AuditColumnsModel audit);

        #endregion Member Search

        #region Member Eligibility
        public List<MemberEligibilityModel> Member_Eligibilty_Get(string MemberId, string SchemeId);
        public List<ConfigurationSchemeViewModel> Member_Eligibilty_Get_By_Scheme(string MemberId, string SchemeGroupId);
        public List<SchemeEligibleFamilyMemberViewModel> Member_Eligible_FamilyMembers_By_SchemeGroup(string MemberId, string SchemeGroupId);
        #endregion Member Eligibility

        #region Member_Detail_Approval_Master_And_History
        public List<MemberDataApprovalMaster> Member_Data_Approval_Master_Get(string Id, string MemberId);
        public List<MemberDataApprovalHistoryView> Member_Data_Approval_History_Get(string Id = "", string RequestId = "");
        public string Member_Detail_Approval_Master_SaveUpdate(MemberDataApprovalMaster memberDataApprovalMaster, AuditColumnsModel audit);
        public string Member_Data_Approval_History_SaveUpdate(MemberDataApprovalHistory memberDataApprovalHistory, AuditColumnsModel audit);
        #endregion Member_Detail_Approval_Master_And_History

        #region Member Document
        public string Member_Document_SaveUpdate(MemberDocumentSaveMaster model, AuditColumnsModel audit);
        public List<MemberDocumentMaster> Member_Document_Get(string Id = "", string MemberId = "", bool IsTemp = false);
        public List<MemberDocumentMaster> Member_NonMandatory_Document_Get(string Id = "", string MemberId = "", bool IsTemp = false);
        public List<MemberDocumentMaster> Family_Member_Document_Get(string Id = "", string MemberId = "", bool IsTemp = false);
        public List<MemberDocumentMaster> Family_Member_NonMandatory_Document_Get(string Id = "", string MemberId = "", bool IsTemp = false);
        public List<MemberDocumentMaster> Member_Document_Get_By_Id(string Id = "", string MemberId = "");
        public IEnumerable<(string OriginalFileName, string SavedFileName)> Member_Document_Get_By_DocCategoryAndMember(string DocumentCategoryId, string MemberId);
        public string Member_Document_Delete(string Id, bool IsTemp, AuditColumnsModel audit);
        public bool Member_Document_Delete_From_Application(string MemberId, string DocumentCategoryId, string ApplicationId = "");
        #endregion Member Document

        #region Dashboard
        public MemberDetailCount MemberDashboardCountGet(string District, string Mobile, string LocalBody, string NameOfLocalBody, string Block, string Corporation, string Municipality, string TownPanchayat, string VillagePanchayat, string Zone);
        #endregion

        #region Member Import
        public string GetMemberImportProcessStatus();
        public void MemberImport(IFormFile postedFile, string path, AuditColumnsModel audit);
        #endregion Member Import

        #region PartialChangeRequest
        public void PartialChangeRequest_Cancel(AuditColumnsModel audit, string Member_Id, string Changed_Detail_Record);
        #endregion PartialChangeRequest

        #region Member Id Card
        public MemberIdCardInfoModel Get_Member_Id_Card(string MemberId);
        #endregion Member Id Card
    }
}
